name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:  
  AZURE_WEBAPP_NAME: az-flower-app   # set this to your App Service name  
  PYTHON_VERSION: '3.11'  
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login  
        uses: azure/login@v2
        with:  
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
                    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }} 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip files for deployment
        run: |
          zip -r release.zip ./* -x '*.git*' 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}     # Your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  
          package: release.zip 
